repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        name: ruff (lint + fix)
        args: [--fix]   # ✅ no 'check' here
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black


